### PR TITLE
Implement API endpoint for OPML import

### PR DESCRIPTION
**Pull request by nto**
Use the opmlparser module by Dan MacTough.
Testing can be improved to check that the feeds are correctly
imported, but it looks like it works fine so far.

### CODE REVIEW

**Comment by devongovett** [comment]
Great! Thanks so much.  Just to clarify, did you actually verify that this works with Google Reader and matches their behavior?  It is listed as untested [here](http://ranchero.com/downloads/GoogleReaderAPI-2009.pdf) and I never got around to that.  If not, that's fine, and we'll just modify it later to conform.  Thanks again!

**Comment by nto** [comment]
I didn't take the time yet to create a test account on Google Reader to verify that it works as documented. That's why some of the errors are generic (Error=Unknown), but it can be easily improved later.

However, I did verify that it loads the OPML exported from my personal account (250 feeds) and the fetcher is able to parse the 4000 posts they contain. This is nice, because now this project is starting to be usable for me, I only need to find (or create) a suitable client user interface. Thanks for merging!

**Comment by lzanita09** [comment]
Does the fetcher normally update the posts every 10 mins for you? It's strange for me that after the first fetch it doesn't fire up another one.

**Comment by devongovett** [comment]
Ok, just tested this with the Google Reader API, and it seems to work as documented.

**Pull request merged**
